name: Deploy to SAP BTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install -g @sap/cds-dk mbt
        npm ci

    - name: Validate MTA
      run: |
        if [ ! -f mta.yaml ]; then
          echo "ERROR: mta.yaml file is missing!"
          exit 1
        fi
        # Validate required fields
        grep -q "_schema-version" mta.yaml || (echo "Missing _schema-version" && exit 1)
        grep -q "ID:" mta.yaml || (echo "Missing ID" && exit 1)
        grep -q "version:" mta.yaml || (echo "Missing version" && exit 1)

    - name: Build project
      run: |
        cds build --production
        mbt build -p=cf --mtar=mta_archives/livestore.mtar

    - name: Install CF CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt update
        sudo apt install cf8-cli
        cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
        cf install-plugin -f -r CF-Community "multiapps"

    - name: Deploy to Cloud Foundry
      env:
        CF_API: ${{ secrets.CF_API }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      run: |
        cf login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORG" -s "$CF_SPACE"
        cf deploy mta_archives/livestore.mtar -f